apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: support
  template:
    metadata:
      labels:
        tier: support
    spec:
      containers:
      - name: counter
        image: lrakai/microservices:counter-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: http://app-tier:8080
          # Service created first to use service environmental variable
          # DNS for service discover
          # Naming pattern
          #   IP address: <service_name>.<service_namespace>
          #   Port: needs to be extracted from SRV DNS record
      - name: poller
        image: lrakai/microservices:poller-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: http://app-tier:$(APP_TIER_SERVICE_PORT)
