apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-spc-res
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "update"]
  resourceNames: ["pod-blue", "pod-name"]
