apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: microservices
spec:
  ports:
  - port: 6379
    protocol: TCP   #default
    name: redis     #optional when only 1 pod
  selector:
    tier: data
  type: ClusterIP   #default