apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: support-tier
  labels:
    app: microservices
    tier: support
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: support-tier
  targetCPUUtilizationPercentage: 70

# Equivalent to
# kubectl autoscale deployment app-tier --max=5 --min=1 --cpu-percent=70