apiVersion: v1
kind: Pod
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app
spec:
  containers:
  - name: server
    image: lrakai/microservices:server-v1
    ports:
    - containerPort: 8080
    env:
    - name: REDIS_URL
      # Environment variable service discovery
      # Naming pattern:
      #   IP address: <all_caps_service_name>_SERVICE_HOST
      #   Port: <all_caps_service_name>_SERVICE_PORT_<all_caps_port_name>
      # All hyphen in name should be replaced by underscore
      value: redis://$(DATA_TIER_SERVICE_HOST):$(DATA_TIER_SERVICE_PORT_REDIS)
      # In multi-container example value was
      # value: redis://localhost:6379
