apiVersion: v1
kind: Pod
metadata:
  name: resr-req
spec:
  containers:
  - name: resr-req-ctr
    image: nginx
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "128Mi"
        cpu: "500m"
        